theme: jekyll-theme-architect

title: log4js2
description: The fast, flexible logger for JavaScript

exclude: ['README.md']

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

highlighter: rouge

github:
  is_project_page: true
  repository_name: "log4js2"
  repository_url: "https://github.com/anigenero/log4js2"
  owner_name: "Robin Schultz"
  owner_url: "https://github.com/anigenero/"